### ISSUE TITLE
Entry Generator

### ISSUE THREAD

**Issue by heukirne** [alientronics/fleetany-api#7]
Manutenção: é quando um pneu tem a pressão normalizada.
Quando um pneu volta a seu estado normal, gerar um entrada de manutenção para o veículo-pneu
Custo será o percentual perdido no valor do pneu

**Comment by felipemelz** [comment]
Na verdade quando a pressão é normalizada, deve-se registrar no sistema não como "manutenção" de forma genérica, mas sim uma "manutenção" de "calibragem". Podendo haver outras inserções de manutenção como recapagem, troca de válvula, correção de vazamento, inserção de manchão, etc..

**Comment by rafaelpv** [comment]
Fiz essa tarefa, pelos testes que fiz localmente ela funciona bem. Só é preciso definir como é calculado o custo (por enquanto deixei 1, que foi o que conversei com o Henrique no Skype). Também não sei se entendi essa questão da manutenção de calibragem. O tipo da entrada que existe lá é apenas "repair", não tem especificação. Como fica, no caso?

**Comment by heukirne** [comment]
Deve criar outros tipos de manutenção padrão para a api utilizar.
Pode criar um entry_type como Manutenção de Calibragem e usar ele no Entry Generator.
